### ISSUE TITLE
I can't see the drop down box when I have too many notebooks

### ISSUE THREAD

**Issue by kN6jq** [laurent22/joplin#10782]
### Operating system

Windows

### Joplin version

Joplin 3.0.13

### Desktop version info

Joplin 3.0.13 (prod, win32)

客户端 ID: b4efd145598648578ac0e2aa7fd16a14
同步版本：3
配置文件版本：47
支持的密钥链：是

修订：599cf5b

Backup: 1.4.1
Outline: 1.5.9

### Current behaviour

I can't see the drop down box when I have too many notebooks
![image](https://github.com/user-attachments/assets/581a1dcd-3313-43b1-a963-96e550c9d7d6)

Please fix the display problem

### Expected behaviour

Please fix the display problem

**Comment by kN6jq** [comment]
use gtp


```css

/* 自定义滚动条的样式 */
.item-list.items::-webkit-scrollbar {
    width: 16px; /* 滚动条的宽度 */
}

.item-list.items::-webkit-scrollbar-track {
    background: #f1f1f1; /* 滚动条轨道的背景色 */
}

.item-list.items::-webkit-scrollbar-thumb {
    background: #888; /* 滚动条的颜色 */
    border-radius: 0; /* 移除圆角 */
}

.item-list.items::-webkit-scrollbar-thumb:hover {
    background: #555; /* 滚动条在鼠标悬停时的颜色 */
}



```
