### ISSUE TITLE
markdown lists cant be styled uniformly by their indentation levels anymore with custom CSS rules, but instead only in first-line, middle-part, last-line

### ISSUE THREAD

**Issue by woodpexer** [laurent22/joplin#11383]
### Operating system

Linux

### Joplin version

3.1.24

### Desktop version info

Joplin 3.1.24 (prod, linux)

Client ID: 71882a53c9644ebdb3ccb34da966a9e0
Sync Version: 3
Profile Version: 47
Keychain Supported: No

Revision: d581264

Backup: 1.4.2
Emoji: 1.0.4
Note Tabs: 1.4.0
Rich Markdown: 0.15.1
Search & Replace: 2.2.0

### context

with update to the CodeMirror 6-based editor, the editor could no longer reference css classes for markdown lists, leading to this [issue](https://github.com/laurent22/joplin/issues/11167).
Big thanks to [@personalizedrefrigerator](https://github.com/personalizedrefrigerator) adding references to list-items with this [#11291](https://github.com/laurent22/joplin/pull/11291)

## previous behavior
in version 3.0.15:  list-items could be styled depending on their indentation levels, because each indentation had its own css class reference with `.cm-variable-2`, `.cm-variable-3`, `.cm-keyword`.
- that allowed me to use Markdown taking notes in a hierarchical way. meaning I organize my notes in a tiered manner with multi level indentations
	- this allows me to zoom out for a higher-level overview or zoom in for detailed understanding. This matters a lot if you write your notes in a logical structured way where indentation levels also carry information like whether a new point is made (no indentation) or if its not a new point but examples or explanations or reasons are made which underline a statement (indentation). With this update markdown lists are only styled by first line, last line, and middle part in between first and last line. 
	- For example
		- Each paragraph starts with a **main statement**.
		- to elaborate the main statement further with details, examples, etc i use **bullet points** which refer to the main statement
		- **sub-bullets** refer to their direct upper bullets, etc
	- this increases the usability for me very much. 

this is how it looks with styled list items by their indentation levels:

<img width="1196" height="896" alt="Image" src="https://github.com/user-attachments/assets/e18ef2f5-3c42-4c08-b7a0-67b5715dab58" />

## current behavior
starting from version 3.1.22: there were no longer any distinct css references there, but instead some generic ones `ͼ3m ͼ3m` which can be somehow referenced by `.cm-orderedList.cm-listItem.cm-line` . 
- Attempting styling markdown lists by those current references results in a non-uniform chaotic styling instead of based on indentation levels, if you are using indentation levels which carry meaning.

this is how it looks attempting to style list items now by their indentation levels:

<img width="1218" height="854" alt="Image" src="https://github.com/user-attachments/assets/64aaee3f-24ee-4423-be4a-dd8bc8167945" />

## for reproduction: my test case for the new markdown editor

custom css styling rules for the new editor:
```CSS

/* first level ordered list */
.cm-orderedList.cm-regionFirstLine.cm-listItem.cm-line {
	color: red !important;
}
  
/* middle level ordered list */
.cm-orderedList.cm-listItem.cm-line {
    color: orange !important;
}

/* last level ordered list */
.cm-orderedList.cm-regionLastLine.cm-listItem.cm-line {
    color: green !important;
}


/* first level unordered list */
.cm-unorderedList.cm-regionFirstLine.cm-listItem.cm-line {
	color: red !important;
}
  
/* middle level unordered list */
.cm-unorderedList.cm-listItem.cm-line {
    color: orange !important;
}

/* last level unordered list */
.cm-unorderedList.cm-regionLastLine.cm-listItem.cm-line {
    color: green !important;
}
```

my markdown text in the new editor
```markdown
normal text: the colors should be consistent, depending on the indentation level, 
and the colors should cycle through the 3 colors (something like: "current indentation level" % 3)
EDIT@07th_January: having the ability to color and style even more than 3 colors would be even better like 5 levels or more and then re-cycling them after 5 colors
1. ordered list level 1 (should be: red)
	1. ordered list level 2 (should be: orange)
- a) unordered list level 1 (should be: red)
- b) unordered list level 1 (should be: red)
- c) unordered list level 1 (should be: red)
	- a) unordered list level 2 (should be: orange)
	- b) unordered list level 2 (should be: orange)
		1. ordered list level 3 (should be: green)
		2. ordered list level 3 (should be: green)
	- c) unordered list level 2 (should be: orange)
- d) unordered list level 1 (should be: red)
	- a) unordered list level 2 (should be: orange)
	- b) unordered list level 2 (should be: orange)
	- c) unordered list level 2 (should be: orange)
		- a) unordered list level 3 (should be: green)
		- b) unordered list level 3 (should be: green)
		- c) unordered list level 3 (should be: green)
			- a) unordered list level 4 (should be: red) <-- level 4 == level 1 colors
				- a) unordered list level 5 (should be: orange) <-- level 5 == level 2 colors
					- a) unordered list level 6 (should be: green) <-- level 6 == level 3 colors
			- b) unordered list level 4 (should be: red)
			- c) unordered list level 4 (should be: red)
		- d) unordered list level 3 (should be: green)
- e) unordered list level 1 (should be: red)

```

result with current behavior, where it is not possible to style list-items depending on their indentation levels:

![result with new editor](https://github.com/user-attachments/assets/25c519e9-3354-46d9-a496-206e24f33435)

## behavior to restore: 
adding code mirror class for lines with list items so that they can be referenced in custom CSS, re-enabling styling list-items depending on their indentation levels 
- the expected behavior is the same as the versions until 3.0.15 where list-items of a markdown list where styled according to their indentation levels, allowing my to not only structure my text in a hierarchical manner, but also style it like that supporting my note structure even more

### for reproduction: my test case for the legacy editor

custom css styling rules for the legacy editor
```CSS
/* Lists (Bullet/number/todo) */
.cm-variable-2 {
	color: red !important;
}
.cm-variable-3 {
    color: orange !important;
}
.cm-keyword {
    color: green !important;
}
```

my markdown text in the legacy editor
```markdown
normal text: the colors should be consistent, depending on the indentation level, 
and the colors should cycle through the 3 colors (something like: "current indentation level" % 3)
1. ordered list level 1 (should be: red)
	1. ordered list level 2 (should be: orange)
- a) unordered list level 1 (should be: red)
- b) unordered list level 1 (should be: red)
- c) unordered list level 1 (should be: red)
	- a) unordered list level 2 (should be: orange)
	- b) unordered list level 2 (should be: orange)
		1. ordered list level 3 (should be: green)
		2. ordered list level 3 (should be: green)
	- c) unordered list level 2 (should be: orange)
- d) unordered list level 1 (should be: red)
	- a) unordered list level 2 (should be: orange)
	- b) unordered list level 2 (should be: orange)
	- c) unordered list level 2 (should be: orange)
		- a) unordered list level 3 (should be: green)
		- b) unordered list level 3 (should be: green)
		- c) unordered list level 3 (should be: green)
			- a) unordered list level 4 (should be: red) <-- level 4 == level 1 colors
				- a) unordered list level 5 (should be: orange) <-- level 5 == level 2 colors
					- a) unordered list level 6 (should be: green) <-- level 6 == level 3 colors
			- b) unordered list level 4 (should be: red)
			- c) unordered list level 4 (should be: red)
		- d) unordered list level 3 (should be: green)
- e) unordered list level 1 (should be: red)
```

result with legacy editor, with correct styling list-items depending on their indentation-levels
![result legacy editor](https://github.com/user-attachments/assets/77e7b4a0-a1bd-43d2-a861-5b9e2c83bd3a)

**Comment by woodpexer** [comment]
The above described reproducable issue with test cases still persists. 

The following css classes still dont exist anymore for the custom css, neither are there any replacements for them in the current release:
```CSS
/* Lists (Bullet/number/todo) */
.cm-variable-2 {
	color: red !important;
}
.cm-variable-3 {
    color: orange !important;
}
.cm-keyword {
    color: green !important;
}
```

I have now re-tested it with:

```
Joplin 3.2.4 (prod, linux)

Client ID: d84ab3fa72fa4cf7889436d4a2374665
Sync Version: 3
Profile Version: 47
Keychain Supported: No

Revision: 1aefcb9

Backup: 1.4.2
Emoji: 1.0.4
Rich Markdown: 0.15.1
Search & Replace: 2.2.0
```
