### ISSUE TITLE
todo problem

### ISSUE THREAD

**Issue by a-Rahmati** [laurent22/joplin#3318]
## Environment

Joplin version: 1.0.216
Platform: Linux
OS specifics: Ubuntu (LDQt) - Lubuntu

## Steps to reproduce
* I already edited userstyle.css like this:
```css
body {
font-family: "Sahel";
direction: rtl;
}

pre {
direction: ltr;
}
```
1. Make a todo list.
2. See the result:
![Selection_347](https://user-images.githubusercontent.com/52320192/83486259-128a0c80-a4be-11ea-9506-49a09c6a72da.png)
