### ISSUE TITLE
Visual indication to the various level of the notes of the Sidebar

### ISSUE THREAD

**Issue by sebastienPoussard** [laurent22/joplin#3767]
Dear Dev Team,
 As discuss in several Forum thread such as [this one](https://discourse.joplinapp.org/t/show-notes-on-notebook-tree/10915/4), It would be a nice feature to have a way to quickly visually identify the level of the different notes in the sidebar.
Could be with **color** or **icon** such as in Cherry :  
![image](https://aws1.discourse-cdn.com/standard14/uploads/cozic/original/2X/8/872ed4cffac32a9c1bd3fb8c8ce945b714d2353f.png)
or maybe with **lines** :  
![lines](https://codesteps.com/wp-content/uploads/2019/07/treeview_control_demo.png)

Best regards.

**Comment by CalebJohn** [comment]
Hi @sebastienPoussard Different notebook levels have an associated `list-item-depth` class attached which will allow a user to customize the lines in any way that's possible with css in [userchrome.css](https://github.com/laurent22/joplin#custom-css).

An example using background colour is below
```css
.list-item-depth-1 {
    background-color: white;
}
list-item-depth-2 {
    background-color: red;
}
list-item-depth-3 {
    background-color: green;
}
```

**Comment by Athalef** [comment]
Hi CalebJohn. Thanks for the info but that's not what Sebastien requested. 
The request is to be able to see the notes themselves in the sidebar with all the rest of the notbooks (without seperating them to the notes bar).
If that's something that can be done by editing userchrome.css file in the profile folder - I'd love to know how to.

**Comment by sebastienPoussard** [comment]
Hi @CalebJohn , 

Thank you for your help !   
I Did modified the file and get some result, I want to modify the CSS and get a more beautiful result.  
Can you tell me where I can find the list of CSS element I can modify?  
example : I want to select only the text part of element `list-item-depth-1`

**Comment by CalebJohn** [comment]
@sebastienPoussard 

Take a look at [this forum comment](https://discourse.joplinapp.org/t/custom-stylesheets/384/36) it will introduce you to discovering elements in Joplin that can be styled.

In your case you just need to add a .list-item flag
for example
```css
.list-item-depth-1 .list-item {
    color: white;
}
list-item-depth-2 .list-item {
    color: red;
}
list-item-depth-3 .list-item {
    color: green;
}
```
This will style just the text color of those lines.
