### ISSUE TITLE
POSTGRES_HOST     No effect

### ISSUE THREAD

**Issue by hqh0803** [laurent22/joplin#4400]
When I saw the launch of Joplin server, I was very happy. I went to have a try

My env file looks like this

[root@hsdb test]# more .env 
DB_CLIENT=pg
POSTGRES_PASSWORD=postgres
POSTGRES_DATABASE=joplin
POSTGRES_USER=postgres
POSTGRES_PORT=5432
POSTGRES_HOST=127.0.0.1

APP_BASE_URL=http://xx.xx.xx.xx:22300
APP_PORT=22300

It all looked normal, and then I tried to start docker

[root@hsdb test]# docker run --env-file .env -p 22300:22300 joplin/server:latest
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.

> @joplin/server@1.7.1 start /home/joplin/packages/server
> node dist/app.js

2021-01-21 07:42:51: App: Starting server (prod) on port 22300 and PID 24...
2021-01-21 07:42:51: App: Running in Docker: true
2021-01-21 07:42:51: App: Public base URL: http://xx.xx.xx.xx:22300
2021-01-21 07:42:51: App: Log dir: /home/joplin/packages/server/logs
2021-01-21 07:42:51: App: DB Config: {
  client: 'pg',
  name: 'joplin',
  user: 'postgres',
  password: '********',
  port: 5432,
  host: 'host.docker.internal'
}
2021-01-21 07:42:51: App: Trying to connect to database...
2021-01-21 07:42:51: db: Could not connect. Will try again. getaddrinfo ENOTFOUND host.docker.internal
2021-01-21 07:42:52: db: Could not connect. Will try again. getaddrinfo ENOTFOUND host.docker.internal
2021-01-21 07:42:53: db: Could not connect. Will try again. getaddrinfo ENOTFOUND host.docker.internal
2021-01-21 07:42:54: db: Could not connect. Will try again. getaddrinfo ENOTFOUND host.docker.internal
2021-01-21 07:42:55: db: Could not connect. Will try again. getaddrinfo ENOTFOUND host.docker.internal
2021-01-21 07:42:56: db: Could not connect. Will try again. getaddrinfo ENOTFOUND host.docker.internal
2021-01-21 07:42:57: db: Could not connect. Will try again. getaddrinfo ENOTFOUND host.docker.internal
2021-01-21 07:42:58: db: Could not connect. Will try again. getaddrinfo ENOTFOUND host.docker.internal
2021-01-21 07:42:59: db: Could not connect. Will try again. getaddrinfo ENOTFOUND host.docker.internal
2021-01-21 07:43:00: db: Could not connect. Will try again. getaddrinfo ENOTFOUND host.docker.internal
2021-01-21 07:43:01: db: Could not connect. Will try again. getaddrinfo ENOTFOUND host.docker.internal
2021-01-21 07:43:02: db: Could not connect. Will try again. getaddrinfo ENOTFOUND host.docker.internal
2021-01-21 07:43:03: db: Could not connect. Will try again. getaddrinfo ENOTFOUND host.docker.internal
2021-01-21 07:43:04: db: Could not connect. Will try again. getaddrinfo ENOTFOUND host.docker.internal
2021-01-21 07:43:05: db: Could not connect. Will try again. getaddrinfo ENOTFOUND host.docker.internal
2021-01-21 07:43:06: db: Could not connect. Will try again. getaddrinfo ENOTFOUND host.docker.internal
2021-01-21 07:43:07: db: Could not connect. Will try again. getaddrinfo ENOTFOUND host.docker.internal
2021-01-21 07:43:08: db: Could not connect. Will try again. getaddrinfo ENOTFOUND host.docker.internal
2021-01-21 07:43:09: db: Could not connect. Will try again. getaddrinfo ENOTFOUND host.docker.internal
2021-01-21 07:43:10: db: Could not connect. Will try again. getaddrinfo ENOTFOUND host.docker.internal
2021-01-21 07:43:11: db: Could not connect. Will try again. getaddrinfo ENOTFOUND host.docker.internal
2021-01-21 07:43:12: db: Could not connect. Will try again. getaddrinfo ENOTFOUND host.docker.internal
2021-01-21 07:43:13: db: Could not connect. Will try again. getaddrinfo ENOTFOUND host.docker.internal
2021-01-21 07:43:14: db: Could not connect. Will try again. getaddrinfo ENOTFOUND host.docker.internal
2021-01-21 07:43:15: db: Could not connect. Will try again. getaddrinfo ENOTFOUND host.docker.internal
2021-01-21 07:43:16: db: Could not connect. Will try again. getaddrinfo ENOTFOUND host.docker.internal
2021-01-21 07:43:17: db: Could not connect. Will try again. getaddrinfo ENOTFOUND host.docker.internal
2021-01-21 07:43:18: db: Could not connect. Will try again. getaddrinfo ENOTFOUND host.docker.internal
2021-01-21 07:43:19: db: Could not connect. Will try again. getaddrinfo ENOTFOUND host.docker.internal
2021-01-21 07:43:20: db: Could not connect. Will try again. getaddrinfo ENOTFOUND host.docker.internal
2021-01-21 07:43:21: db: Could not connect. Will try again. getaddrinfo ENOTFOUND host.docker.internal
2021-01-21 07:43:21: [error] db: Timeout trying to connect to database: Error: getaddrinfo ENOTFOUND host.docker.internal
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)
From previous event:
    at Client_PG.acquireRawConnection (/home/joplin/packages/server/node_modules/knex/lib/dialects/postgres/index.js:108:12)
    at create (/home/joplin/packages/server/node_modules/knex/lib/client.js:258:21)
    at /home/joplin/packages/server/node_modules/tarn/lib/Pool.js:389:34
    at Object.tryPromise (/home/joplin/packages/server/node_modules/tarn/lib/utils.js:53:24)
    at /home/joplin/packages/server/node_modules/tarn/lib/Pool.js:389:17
    at new Promise (<anonymous>)
    at callbackOrPromise (/home/joplin/packages/server/node_modules/tarn/lib/Pool.js:380:12)
    at Pool._create (/home/joplin/packages/server/node_modules/tarn/lib/Pool.js:290:9)
    at Pool._doCreate (/home/joplin/packages/server/node_modules/tarn/lib/Pool.js:260:36)
    at Pool._tryAcquireOrCreate (/home/joplin/packages/server/node_modules/tarn/lib/Pool.js:211:18)
    at Pool.acquire (/home/joplin/packages/server/node_modules/tarn/lib/Pool.js:117:14)
    at /home/joplin/packages/server/node_modules/knex/lib/client.js:312:43
From previous event:
    at Client_PG.acquireConnection (/home/joplin/packages/server/node_modules/knex/lib/client.js:312:26)
    at Runner.ensureConnection (/home/joplin/packages/server/node_modules/knex/lib/runner.js:246:8)
    at Runner.run (/home/joplin/packages/server/node_modules/knex/lib/runner.js:25:27)
    at Builder.Target.then (/home/joplin/packages/server/node_modules/knex/lib/interface.js:14:43) {
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'host.docker.internal'
}
Error: Timeout trying to connect to database. Last error was: getaddrinfo ENOTFOUND host.docker.internal
    at Object.<anonymous> (/home/joplin/packages/server/src/db.ts:93:10)
    at Generator.next (<anonymous>)
    at fulfilled (/home/joplin/packages/server/dist/db.js:5:58)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @joplin/server@1.7.1 start: `node dist/app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @joplin/server@1.7.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/joplin/.npm/_logs/2021-01-21T07_43_21_739Z-debug.log

He told me that I couldn't get to the database, but my .env  didn't seem to have any problems

I'm trying to host.docker.internal Add my hosts file

[root@hsdb test]# echo "127.0.0.1 host.docker.internal" >> /etc/hosts

Then I try to start docker again

[root@hsdb test]# docker run --env-file .env -p 22300:22300 joplin/server:latest
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.

> @joplin/server@1.7.1 start /home/joplin/packages/server
> node dist/app.js

2021-01-21 07:46:40: App: Starting server (prod) on port 22300 and PID 24...
2021-01-21 07:46:40: App: Running in Docker: true
2021-01-21 07:46:40: App: Public base URL: http://xx.xx.xx.xx:22300
2021-01-21 07:46:40: App: Log dir: /home/joplin/packages/server/logs
2021-01-21 07:46:40: App: DB Config: {
  client: 'pg',
  name: 'joplin',
  user: 'postgres',
  password: '********',
  port: 5432,
  host: 'host.docker.internal'
}
2021-01-21 07:46:40: App: Trying to connect to database...
2021-01-21 07:46:40: App: Connection check: { latestMigration: null, isCreated: false, error: null }
2021-01-21 07:46:40: App: Migrating database...
2021-01-21 07:46:41: App: Call this for testing: `curl http://xx.xx.xx.xx:22300/api/ping`
2021-01-21 07:47:13: App: GET /api/ping
2021-01-21 07:47:13: App: GET /favicon.ico
2021-01-21 07:47:13: [error] App: 404: GET /favicon.ico : Path not found: favicon.ico

He succeeded, that is  .env   POSTGRES_HOST  has no effect

**Comment by laurent22** [comment]
What Docker version?

**Comment by hqh0803** [comment]
> What Docker version?

[root@shen ~]# docker --version
Docker version 20.10.2, build 2291f61

I installed it through yum

**Comment by laurent22** [comment]
That should work then. What happens is that your "localhost" is translated to "host.docker.internal", which is a built-in host that Docker uses to access the local network. Why it's not finding this within your container. You might have more luck asking on a Docker-related forum or StackOverflow.

**Comment by hqh0803** [comment]
okay, thank you

**Comment by linuxbuh** [comment]
You need to add docker run --env-file .env -p 22300: 22300 joplin / server: latest to the run line
parameter --net = host
It should be like this docker run --env-file .env --net = host -p 22300: 22300 joplin / server: latest
Please correct it in the documentation.

**Comment by dzusan** [comment]
`--net=host` do not work for me
Docker version 20.10.5, build 55c4c88966
But `docker run --env-file .env --add-host=host.docker.internal:host-gateway -p 22300:22300 joplin/server:latest` works properly ([link](https://stackoverflow.com/a/61424570))

**Comment by httpjamesm** [comment]
I'm also having this issue. None of the solutions above worked for me.

**Comment by jdelibas** [comment]
Just ran into this myself. `host.docker.internal` isnt available on linux hosts.
Its probably safer to use  `172.17.0.1` instead which i believe is available on mac hosts.

Its probably even safer to not mess with configuration vars in container/host enviroments and use docker-compose networking to reference the containers via their hostname within the network.

```yaml
version: '3'
services:
  app:
    image: joplin/server:latest
    ports:
      - "22300:22300"
    environment:
      - DB_CLIENT=pg
      - POSTGRES_PASSWORD=joplin
      - POSTGRES_DATABASE=joplin
      - POSTGRES_USER=joplin
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
    networks:
        - joplin
  db:
    image: postgres:13.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=joplin
      - POSTGRES_USER=joplin
      - POSTGRES_DB=joplin
    networks: 
      - joplin

networks:
  joplin:
    driver: bridge
```

**Comment by nextcloudfan** [comment]
Nothing fixed, Problem still exists. Facing the same problem

**Comment by donwilson** [comment]
Hope this helps someone.

This setup utilizes a separate, already preconfigured and running Traefik+cloudflare/cloudflared tunnel for simplistic SSL. That configuration creates an external network named `gateway` that other compose projects connect to. Happy to share my setup for this, just let me know.

This does not unnecessarily expose sensitive ports like other Joplin examples do.

```yml
# docker-compose.yml

networks:
  default:
    name: gateway
    external: true

services:
  postgres:
    image: postgres:16
    volumes:
      - ./.docker/postgres/data:/var/lib/postgresql/data
    restart: unless-stopped
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DATABASE}
  joplinsync:
    image: joplin/server:latest
    depends_on:
      - postgres
    expose:
      - 22300
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIME_ZONE}
      - APP_PORT=${APP_PORT}
      - APP_BASE_URL=${APP_BASE_URL}
      - DB_CLIENT=${DB_CLIENT}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=postgres
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.redirect-https.redirectScheme.scheme=https"
      - "traefik.http.middlewares.redirect-https.redirectScheme.permanent=true"
      - "traefik.http.routers.joplinsync-public-https.rule=Host(`${HOSTNAME_JOPLIN_PUBLIC}`)"
      - "traefik.http.routers.joplinsync-public-https.entrypoints=${TRAEFIK_ENTRYPOINT_HTTPS}"
      - "traefik.http.routers.joplinsync-public-https.tls=true"
      - "traefik.http.routers.joplinsync-public-https.service=joplinsync"
      - "traefik.http.routers.joplinsync-public-http.rule=Host(`${HOSTNAME_JOPLIN_PUBLIC}`)"
      - "traefik.http.routers.joplinsync-public-http.entrypoints=${TRAEFIK_ENTRYPOINT_HTTP}"
      - "traefik.http.routers.joplinsync-public-http.middlewares=redirect-https"
      - "traefik.http.routers.joplinsync-public-http.service=joplinsync"
      - "traefik.http.routers.joplinsync.rule=Host(`${HOSTNAME_JOPLIN}`)"
      - "traefik.http.routers.joplinsync.entrypoints=${TRAEFIK_ENTRYPOINT_HTTP}"
      - "traefik.http.routers.joplinsync.service=joplinsync"
      - "traefik.http.services.joplinsync.loadbalancer.server.port=${APP_PORT}"
```

```env
# .env

COMPOSE_PROJECT_NAME=joplin

# User / Date
PUID=1000
PGID=1000
TIME_ZONE=America/Chicago

# Hostnames
HOSTNAME_JOPLIN=joplin.lan   # technically not useful but left here nonetheless
HOSTNAME_JOPLIN_PUBLIC=joplin.yourdomain.com   # change this to your Cloudflare Tunnel subdomain

# Traefik
TRAEFIK_NETWORK_NAME=gateway
TRAEFIK_ENTRYPOINT_HTTP=http
TRAEFIK_ENTRYPOINT_HTTPS=https

# Database
DB_CLIENT=pg
POSTGRES_PASSWORD=16CharPassword
POSTGRES_DATABASE=joplin
POSTGRES_USER=joplin
POSTGRES_PORT=5432

# Joplin
APP_PORT=22300
APP_BASE_URL='https://joplin.yourdomain.com'
```

This is only accessible through the `HOSTNAME_JOPLIN_PUBLIC` domain created in your Cloudflare Tunnel setup.

**Comment by UnicornUnderMoon** [comment]
It work for me.
joplin server in docker, use POSTGRES in host.At first,`host.docker.internal` isn't available on linux hosts.
```
version: '3'
services:
  joplin-server:
    image: joplin/server:latest
    container_name: joplin-server
    ports:
      - "{port}:22300"
    restart: always
    environment:
      - APP_PORT=22300
      - APP_BASE_URL={your domain}
      - DB_CLIENT=pg
      - POSTGRES_PASSWORD={password}
      - POSTGRES_DATABASE=joplindb
      - POSTGRES_USER=joplin
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=192.168.1.10
```
About POSTGRES_HOST, do not use 127.0.0.1, this URL refers to docker's internal。
Use something like 192.168.1.10, which is the address of my POSTGRES host on the LAN, or you can use the gateway address of the network where the container joplin server is located.
Don't forget to set `listen_addresses = '*'` in the `postgresql.conf` file and the URL of the listening joplin server container in the `pg_hba.conf` file `host joplindb joplin 192.168.0.1/16 scram-sha-256`
