### ISSUE TITLE
jest 26.6.3 in fork-htmlparser2's package.json breaks offline build(flatpak)

### ISSUE THREAD

**Issue by catsout** [laurent22/joplin#4478]
Flatpak in flathub require building **without network access**.
And it's done by pregenerating all file needed by npm, and put them to npm cache.
The generation is **based on the package-lock.json**.

But here at the **package.json** has a **higher main version** of jest than **package-lock.json**.
Which cause npm request https://registry.npmjs.org/jest and breaks the build.
```
npm sill install loadAllDepsIntoIdealTree
npm sill fetchPackageMetaData error for jest@^26.6.3 request to https://registry.npmjs.org/jest failed: cache mode is 'only-if-cached' but no cached response available.
```
[full log](https://flathub.org/builds/#/builders/8/builds/4552/steps/6/logs/stdio)

package.json
```
'jest': '^26.6.3'
```
package-lock.json 
```
        "jest": {
            "version": "24.9.0",
            "resolved": "https://registry.npmjs.org/jest/-/jest-24.9.0.tgz",
            "integrity": "sha512-YvkBL1Zm7d2B1+h5fHEOdyjCG+sGMz4f8D86/0HiqJ6MB4MnDc8FgP5vdWsGnemOQro7lnYo8UakZ3+5A0jxGw==",
            "dev": true,
            "requires": {
                "import-local": "^2.0.0",
                "jest-cli": "^24.9.0"
            }
```

So, I think updating package-lock.json will be fine.
And I already test it, build ok.
Patch jest to 24.8.0, works too.

**Comment by catsout** [comment]
build script
```yaml
    env:
        npm_config_cache: /run/build/joplin/flatpak-node/npm-cache
        npm_config_nodedir: /usr/lib/sdk/node12
        npm_config_offline: 'true'
        npm_config_no_save: 'true'
        npm_config_loglevel: verbose
    build-commands:
      - npm install
      - mkdir -p packages/app-desktop/dist && touch packages/app-desktop/dist/AppImage
      - |
        cd packages/app-desktop
        npm run dist -- --dir --linux dir
```
