### ISSUE TITLE
[server] APP_BASE_URL with reverse proxy incompatibility

### ISSUE THREAD

**Issue by fourstepper** [laurent22/joplin#4652]
Right now, Joplin Server requires the full URL including the protocol to be passed for listening in the APP_BASE_URL variable - this can create substantial issues when used in tandem with a TLS-terminating reverse proxy - in my case, that proxy is traefik, but the proxy in use I think doesn't really matter to replicate this issue.

I have not been able to figure out how to properly terminate SSL and direct traffic to Joplin in order for Joplin like it and behave well.

**I have tried these combinations which didn't work:**

1.) APP_BASE_URL without protocol schema

`APP_BASE_URL=domain.com`
        
```
- "traefik.http.routers.joplin.rule=Host(`domain.com`)"
- "traefik.http.routers.joplin.entrypoints=websecure"
```

2.) APP_BASE_URL with protocol schema (HTTP Joplin + HTTPS proxy)

`APP_BASE_URL=http://domain.com`
        
```
- "traefik.http.routers.joplin.rule=Host(`domain.com`)"
- "traefik.http.routers.joplin.entrypoints=websecure"
```

3.) APP_BASE_URL with protocol schema (HTTPS Joplin + HTTPS proxy)

`APP_BASE_URL=https://domain.com`
        
```
- "traefik.http.routers.joplin.rule=Host(`domain.com`)"
- "traefik.http.routers.joplin.entrypoints=websecure"
```
**The only combination that worked for me:**

`APP_BASE_URL=http://domain.com`
        
```
- "traefik.http.routers.joplin.rule=Host(`domain.com`)"
- "traefik.http.routers.joplin.entrypoints=web"
```

_Legend_
`web` entrypoint listens on port 80 and directs traffic to Joplin's port 22300, unencrypted HTTP.
`websecure` entrypoint generates a self-signed certificate (or requests a Let's Encrypt certificate), proxy listens on port 443 and directs traffic to Joplin's port 22300, unencrypted HTTP.

Here is the docker-compose used:

```
---
version: '3'
services:

    traefik:
        image: "traefik:v2.4.7"
        container_name: "traefik"
        restart: always
        command:
            - "--log.level=DEBUG"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entrypoints.web.address=:80"
            - "--entrypoints.websecure.address=:443"
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"

    db:
        image: postgres:13.1
        ports:
            - "5432:5432"
        restart: unless-stopped
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_DB=${POSTGRES_DATABASE}
    app:
        image: joplin/server:latest
        depends_on:
            - db
        expose:
            - "22300"
        restart: unless-stopped
        environment:
            - APP_BASE_URL=${APP_BASE_URL}
            - APP_PORT=22300
            - DB_CLIENT=pg
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DATABASE=${POSTGRES_DATABASE}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PORT=${POSTGRES_PORT}
            - POSTGRES_HOST=db
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.joplin.rule=Host(`domain.com`)"
            # as described in the issue, this has changed back and forth
            - "traefik.http.routers.joplin.entrypoints=websecure 
```

and the .env:

```
APP_BASE_URL=domain.com
APP_PORT=22300
DB_CLIENT=pg
POSTGRES_DATABASE=joplin
POSTGRES_USER=joplin
POSTGRES_PASSWORD=pa$$word
POSTGRES_PORT=5432
POSTGRES_HOST=localhost
```

Please note that I have domain.com pointed to 127.0.0.1 for testing purposes in my /etc/hosts

The curious part for me is that the whole joplin server as packaged in the `joplin/server:latest` expects the APP_BASE_URL variable in order to return URLs based on that URL, which doesn't seem good design.
            
I think the best way to handle this would be to be protocol agnostic and listen on localhost only, while returning the requested domain for each call to the back-end based on the `Host: ` header - this way, every proxy will behave well regardless of the protocol used. As it's not possible to run the Joplin server without a proxy over HTTPS, I think having first-class proxy support is a priority, but I am open to any ideas that could be better to handle this correctly.
