### ISSUE TITLE
Joplin Server in a single Pod on Kubernetes can't access postgresql

### ISSUE THREAD

**Issue by lsascha** [laurent22/joplin#5048]
## Environment

Joplin Server version: 2.0.5-beta
Platform: Bare Metal Kubernetes (Linux)

1. Create a single Pod with the Joplin Server and postgreSQL Container
2. Define the ENV variables for Joplin Server to access postgreSQL.
3. Since all Containers in a Pod communicate whith each other using 127.0.0.1 or localhost, 
    POSTGRES_HOST has to be 127.0.0.1 or localhost.

## Describe what you expected to happen
I expected it to use the IP 127.0.0.1 or "localhost" to reach the postgreSQL Databse.

But it actually used "host.docker.internal".
I found this part in the Code:
https://github.com/laurent22/joplin/blob/770af6a53b3aa5bdd9b88e4734f0b636c15734d0/packages/server/src/config.ts#L51-L55

Which i guess is the reason for this.

In my opinion, when someone uses "localhost" or "127.0.0.1", it should really use these, and not secretly use something different.
Another thing is, that "host.docker.internal" should not even work on a Linux Host machine when using Docker since that is a long standing open issue for Docker on Linux. (see this issue: https://github.com/docker/for-linux/issues/264)

So i suggest just use the defined Host, and just document to people to use "host.docker.internal" on Mac or Win when they want to access the host.

## Logfile
```
2021-06-03 18:57:00: App: DB Config: {
client: 'pg',
name: 'joplin',
user: 'joplin',
password: '********',
port: 5432,
host: 'host.docker.internal'
}
2021-06-03 18:57:00: App: Trying to connect to database...
2021-06-03 18:57:00: db: Could not connect. Will try again. getaddrinfo ENOTFOUND host.docker.internal
```

**Comment by lsascha** [comment]
As a workaround i now used

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: joplin-server
spec:
  restartPolicy: Always
  hostAliases:
  - ip: "127.0.0.1"
    hostnames:
    - "actual.localhost"
# ...
  containers:
  - name: joplin-server
    image: joplin/server:2.0.5-beta
    env:
    - name: POSTGRES_HOST
      value: "actual.localhost"
# ...
```

which adds a new entry to the hosts file on all containers in the pod
