### ISSUE TITLE
No login or signup possible with joplin server

### ISSUE THREAD

**Issue by danielfomin96** [laurent22/joplin#5089]
Hello,

It is for me not possible to create or manage any users on my joplin server. I started my old installation with version 1.x and incrementally upgraded to 2.0.13. I had the problem that I could not manage to login with the existing users or create new users somewhere around 2.0.6. Trying to solve this I started fresh by deleting the database. 
After this I still could not create users.

## Environment

Joplin version: Joplin Server 2.0.13
Platform: Linux 
OS specifics: Ubuntu, Docker, Nginx reverse proxy

## Steps to reproduce

1. Start fresh joplin server
2. Go to /signup
3. Input form data
4. Submit

## Describe what you expected to happen
New user is created without problem

## Logfile
```
app_1        |   TypeError [ERR_INVALID_URL]: Invalid URL: null
app_1        |       at onParseError (internal/url.js:258:9)
app_1        |       at new URL (internal/url.js:334:5)
app_1        |       at acceptOrigin (/home/joplin/packages/server/src/app.ts:104:21)
app_1        |       at Object.origin (/home/joplin/packages/server/src/app.ts:122:8)
app_1        |       at cors (/home/joplin/packages/server/node_modules/@koa/cors/index.js:60:24)
app_1        |       at dispatch (/home/joplin/packages/server/node_modules/koa-compose/index.js:42:32)
app_1        |       at /home/joplin/packages/server/node_modules/koa-compose/index.js:34:12
app_1        |       at Application.handleRequest (/home/joplin/packages/server/node_modules/koa/lib/application.js:162:12)
app_1        |       at Server.handleRequest (/home/joplin/packages/server/node_modules/koa/lib/application.js:144:19)
app_1        |       at Server.emit (events.js:314:20)
```

## Docker-compose.yml

```
version: '3'

services:
    db:
        image: postgres:13.1
        restart: unless-stopped
        volumes:
          - ./db:/var/lib/postgresql/data
        environment:
            - APP_PORT=22300
            - POSTGRES_PASSWORD=xxxxx
            - POSTGRES_USER=joplin
            - POSTGRES_DB=joplin
    app:
        image: joplin/server:latest
        depends_on:
            - db
        ports:
            - "22300:22300"
        restart: unless-stopped
        environment:
            - APP_BASE_URL=https://joplin.example.com
            - DB_CLIENT=pg
            - POSTGRES_PASSWORD=xxxxx
            - POSTGRES_DATABASE=joplin
            - POSTGRES_USER=joplin
            - POSTGRES_PORT=5432
            - POSTGRES_HOST=db
```
