### ISSUE TITLE
Joplin Server 2.x Docker Image breaks ability to run as non-root user

### ISSUE THREAD

**Issue by agrider** [laurent22/joplin#5100]
## Environment

Joplin version: 2.0.11, though not really relevant since this is a server startup failure before ever interacting
Platform: Docker Image of Joplin-Server 2.1.1
OS specifics: 

## Steps to reproduce

1.  Run the docker image as a non-root user in docker such as in docker-compose, via `user: "123:123"`.
2. Start the container.
3. Previously the container would start just fine and happily run as the more secure, non-root user. Now, the container will fail to start as it is attempting to write directories on permission denied errors. It appears as though this is because the container is now utilizing the user's home directory to store logs. 
```
> @joplin/server@2.1.1 start /home/joplin/packages/server
> node dist/app.js

[Error: EACCES: permission denied, mkdir '/home/joplin/packages/server/logs'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/home/joplin/packages/server/logs'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @joplin/server@2.1.1 start: `node dist/app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @joplin/server@2.1.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
`

<!--
  Issues without reproduction steps are likely to stall.
-->

## Describe what you expected to happen
Expected the container to start successfully as it did on all previous 1.x versions.


## Logfile

<!--
  Please attach a debug log. Issues without a debug log are likely to stall.
  For information on how to collect a log file: https://joplinapp.org/debugging/
-->

**Comment by tedtms** [comment]
Hey,

Can you provide your docker-compose YML? I'm running server version 2.1.6 currently and have no issues, also running joplin-server as a non-root user.

**Comment by agrider** [comment]
Sure. Here are the relevant pieces of the compose, since it's a much larger file that manages 30ish of my non-critical home docker services. The line that breaks startup is `user: UID:GID`. Removing that line (and hence allowing the container to run mapped to root on the host machine) corrects the problem. 

``` yaml

x-user: &user
  user: "validUID:validGID" //correspond to owner/group of the folder all mounts access, though joplin doesn't have any mounts
x-service-defaults-with-network: 
  &defaultsWithNetwork
  restart: unless-stopped
  mem_limit: 3g
  cpus: "2.0"
  cpu_shares: 1024
  networks: &network
    - generalbridge

---SNIP---

joplin-server:
    << : *defaultsWithNetwork
    << : *user
    image: joplin/server:2.1.2
    container_name: "joplin-server"
    depends_on:
      - postgres
    ports:
      - obfuscated:ports
    env_file: /nfs/docker/joplin-server/joplin-server.env
    labels:
      diun.enable: "true"
      diun.watch_repo: "true"
      diun.exclude_tags: "\\.*-beta"
```

All the config is valid and correct (including references I didn't copy like the bridge config), working prior to the update to the 2.x image. Removing the remapping of the container user allows successful startup. Also, I am still running 2.1.2, so it is possible this is fixed in subsequent images, but I haven't switched as they are all tagged -beta.
