### ISSUE TITLE
Joplin Server fails on reverse proxy with "Invalid origin"

### ISSUE THREAD

**Issue by jansende** [laurent22/joplin#5300]
I have successfully set up Joplin in a local docker container. I am now trying to pass it to my private domain using a reverse proxy, but it is not working.

## Environment

Joplin version: 2.1.2
Platform: Linux NAS
OS specifics: Docker

```yaml
version: '3'

services:
    db:
        image: postgres:13.1
        volumes:
            - /local/path:/var/lib/postgresql/data
        restart: unless-stopped
        environment:
            - APP_PORT=22300
            - POSTGRES_PASSWORD=********
            - POSTGRES_USER=user
            - POSTGRES_DB=database
    app:
        image: joplin/server:2.1.2
        depends_on:
            - db
        ports:
            - "22300:22300"
        restart: unless-stopped
        environment:
            - APP_PORT=22300
            - APP_BASE_URL=http://192.168.1.2:22300/
            - DB_CLIENT=pg
            - POSTGRES_PASSWORD=********
            - POSTGRES_DATABASE=database
            - POSTGRES_USER=user
            - POSTGRES_PORT=5432
            - POSTGRES_HOST=db
```

## Steps to reproduce

1. I setup an nginx reverse proxy using the following configuration.
```nginx
server {
    listen 80;
    listen [::]:80;
    server_name my.example.org;

    location / {
        proxy_pass http://192.168.1.2:22300;
    }
}
```
2. When trying to access Joplin via my.example.org, the connection fails with error 502: Bad Gateway
3. nginx provides the following message:
```
2021/08/13 02:44:08 [error] 24#24: *4 upstream timed out (110: Connection timed out) while connecting to upstream, client: 123.45.67.89, server: my.example.org, request: "GET / HTTP/1.1", upstream: "http://192.168.1.2:22300/", host: "my.example.org"
```
4. Joplin itself provides the following:
```
2021-08-13 02:44:08: [error] App: 404: GET / : Invalid origin: http://127.0.0.1:22300
```

When using the local http://192.168.1.2:22300/ instead, everything works fine.

## Describe what you expected to happen
As the nginx configuration I am using works fine with my other services, I expect this to be an issue with the Joplin Server. Maybe, the forwarded messages are not handled properly?
