### ISSUE TITLE
Bright background around code block insertion dialog in dark mode

### ISSUE THREAD

**Issue by pshirshov** [laurent22/joplin#5310]
TBH these white splashes are quite painful.

This usercss helps:

```css
.tox .tox-dialog-wrap__backdrop {
background-color: #303030 !important;
}
```

Though I think that should work out of the box. Could you fix that?

Thanks

<img width="1533" alt="Screenshot 2021-08-14 at 16 01 35" src="https://user-images.githubusercontent.com/295225/129450537-77840706-6909-446a-8aaa-d8c0cee81b10.png">
