### ISSUE TITLE
Appearance changes in the 2.6.2 version

### ISSUE THREAD

**Issue by antoniopaolini** [laurent22/joplin#5783]
Hello everybody.
Going from 2.5.12 to 2.6.2 I see some little but disturbing changes in the appearance.

1. The button text site is bigger:
It changed from 13px to 16px.
Another user found the change here: https://discourse.joplinapp.org/t/buttons-text-looks-too-big/21914/3?u=antoniopaolini

2.  The notebook list items had a lot of space between elements, like in the gmail's "comfortable density" setting. Very ugly.
The height changed from 25px to 30px.

I restored the previous behavior whit the userchrome.css:
```css
button {
	font-size: 13px;
	/*font-size: unset;*/
	}
.list-item-container {
	height: 25px !important;
}

```

## Environment
Joplin 2.6.2 (prod, win32)

ID del Client: 6c64c797f00b410c98d19c8697f4355e
Sinc. versione: 3
Profilo versione: 41
Portachiavi supportato: No

Revisione: 5a82f5d

## Steps to reproduce

1. Open the application and look at the notebook list
2. Also in the settings page the button have a bigger text
