### ISSUE TITLE
Can't enter to my joplin server

### ISSUE THREAD

**Issue by Onefabis** [laurent22/joplin#5897]
Here is my portainer stack settings:
```
version: '3'

services:
    db:
        image: postgres:latest 
        container_name: postgres 
#        ports:
#            - 5433:5432 
        restart: unless-stopped 
        volumes:
            - /srv/dev-disk-by-uuid-faa85cb3-3ef8-4ee7-b7fe-fb248daa00b9/joplindb:/postgresql/data # Make database files persistent. Otherwise data is lost when the container is destroyed.
        environment:
            - APP_PORT=22300 # port joplin-server is reachable at
            - POSTGRES_PASSWORD=*** #  database password
            - POSTGRES_USER=admin #  database user
            - POSTGRES_DB=joplin #  database name
    app:
        image: joplin/server:latest
        depends_on:
            - db
        ports:
            - "22300:22300" # Expose internal port to LAN
        restart: unless-stopped
        environment:
            - APP_BASE_URL=http://192.168.88.35:22300 # <- HERE
            - DB_CLIENT=pg
            - POSTGRES_PASSWORD=*** 
            - POSTGRES_DATABASE=joplin 
            - POSTGRES_USER=admin
            - POSTGRES_PORT=5432 
            - POSTGRES_HOST=db

```
Was able to login few days ago on the new account created on Windows and Android clients and sync without any problems. 
But now I can't sync on both clients,  the error is the same:
select * from "users" where "email" = $1 limit $2 - relation "users" does not exist (Code 42P01)
