### ISSUE TITLE
Joplin Server not getting recognized by Traefik v2 in Docker Swarm

### ISSUE THREAD

**Issue by NK0D1NG** [laurent22/joplin#6248]
## Environment

Joplin version: see docker-compose file
Platform: Linux
OS specifics: Ubuntu Server 20.04 LTS

## Steps to reproduce

1. Create Docker-Cmopose file
2. Deploy it using Docker swarm
3. Watch Traefik Dashboard

## Describe what you expected to happen
Traefik picking up the Joplin Server as a service and the service to be reachable via HTTPS. All my other services are working perfectly fine with Traefik 2 in the Swarm. Just the Joplin Server is not getting picked up. So I think this is Joplin Server related, because the config of all other services is similar (especially the labels).

## Docker-Compose File
```
version: '3.5'
services:
    db:
      image: postgres:13.1
      volumes:
          - joplin:/var/lib/postgresql/data
      environment:
          - POSTGRES_PASSWORD=dbpassword
          - POSTGRES_USER=joplin
          - POSTGRES_DB=joplin
      networks:
          - joplin
      deploy:
        replicas: 1
        update_config:
          parallelism: 1
          delay: 10s
        restart_policy:
          condition: on-failure
      labels:
        - "traefik.enable=false"
    app:
      image: joplin/server:latest
      depends_on:
          - db
      environment:
          - APP_BASE_URL=https://joplin.mydomain.de
          - APP_PORT=22300
          - DB_CLIENT=pg
          - POSTGRES_PASSWORD=dbpassword
          - POSTGRES_DATABASE=joplin
          - POSTGRES_USER=joplin
          - POSTGRES_PORT=5432
          - POSTGRES_HOST=db
      networks:
          - traefik-public
          - joplin
      ports:
        - "22300:22300"
      deploy:
        replicas: 1
        update_config:
          parallelism: 1
          delay: 10s
        restart_policy:
          condition: on-failure
      labels:
          - "traefik.enable=true"
          - "traefik.docker.network=traefik-public"
          - traefik.http.routers.joplin.rule=Host(`joplin.mydomain.de`)
          - traefik.http.routers.joplin.entrypoints=https
          - "traefik.http.routers.joplin.tls=true"
          - "traefik.http.routers.joplin.tls.certresolver=mycertresolver"
          - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto = http"
          - "traefik.http.routers.joplin.service=joplin-server"
          - "traefik.http.services.joplin-server.loadbalancer.passhostheader=true"
          - "traefik.http.services.joplin-server.loadbalancer.server.port=22300"
networks:
  joplin:
    driver: overlay
  traefik-public:
    external: true

volumes:
 joplin:
   driver_opts:
     type: "nfs"
     o: "addr=nfsserver,nolock,soft,rw"
     device: ":/srv/storage/joplin"

```

## Logfile
```
joplin_app.1.yi95w6wy71yq@v2202112142320170882    | 2022-03-08 22:34:42: App: Mailer Config: {
joplin_app.1.yi95w6wy71yq@v2202112142320170882    |   enabled: false,
joplin_app.1.yi95w6wy71yq@v2202112142320170882    |   host: '',
joplin_app.1.yi95w6wy71yq@v2202112142320170882    |   port: 465,
joplin_app.1.yi95w6wy71yq@v2202112142320170882    |   security: 'tls',
joplin_app.1.yi95w6wy71yq@v2202112142320170882    |   authUser: '',
joplin_app.1.yi95w6wy71yq@v2202112142320170882    |   authPassword: '********',
joplin_app.1.yi95w6wy71yq@v2202112142320170882    |   noReplyName: '',
joplin_app.1.yi95w6wy71yq@v2202112142320170882    |   noReplyEmail: ''
joplin_app.1.m26uaen8d6nz@v2202112142320170882    | 2022-03-08 22:30:00: TaskService: Completed #3 (Process oversized accounts) in 32ms
joplin_app.1.yi95w6wy71yq@v2202112142320170882    | }
joplin_app.1.yi95w6wy71yq@v2202112142320170882    | 2022-03-08 22:34:42: App: Content driver: { type: 1 }
joplin_app.1.yi95w6wy71yq@v2202112142320170882    | 2022-03-08 22:34:42: App: Content driver (fallback): null
joplin_app.1.yi95w6wy71yq@v2202112142320170882    | 2022-03-08 22:34:42: App: Trying to connect to database...
joplin_app.1.yi95w6wy71yq@v2202112142320170882    | 2022-03-08 22:34:42: db: Could not connect. Will try again. getaddrinfo ENOTFOUND db
joplin_app.1.yi95w6wy71yq@v2202112142320170882    | 2022-03-08 22:34:43: App: Connection check: {
joplin_app.1.yi95w6wy71yq@v2202112142320170882    |   latestMigration: { name: '20220201151223_backup_items.js', done: true },
joplin_app.1.yi95w6wy71yq@v2202112142320170882    |   isCreated: true,
joplin_app.1.yi95w6wy71yq@v2202112142320170882    |   error: null
joplin_app.1.yi95w6wy71yq@v2202112142320170882    | }
joplin_app.1.yi95w6wy71yq@v2202112142320170882    | 2022-03-08 22:34:43: App: Auto-migrating database...
joplin_app.1.yi95w6wy71yq@v2202112142320170882    | 2022-03-08 22:34:43: App: Latest migration: { name: '20220201151223_backup_items.js', done: true }
joplin_app.1.yi95w6wy71yq@v2202112142320170882    | 2022-03-08 22:34:43: App: Performing main storage check...
joplin_app.1.yi95w6wy71yq@v2202112142320170882    | 2022-03-08 22:34:43: App: Database storage is special and cannot be checked this way. If the connection to the database was successful then the storage driver should work too.
joplin_app.1.yi95w6wy71yq@v2202112142320170882    | 2022-03-08 22:34:43: App: Starting services...
joplin_app.1.yi95w6wy71yq@v2202112142320170882    | 2022-03-08 22:34:43: ShareService: Starting maintenance...
joplin_app.1.yi95w6wy71yq@v2202112142320170882    | 2022-03-08 22:34:43: EmailService: Service will be disabled because mailer config is not set or is explicitly disabled
joplin_app.1.yi95w6wy71yq@v2202112142320170882    | 2022-03-08 22:34:43: TaskService: Scheduling #1 (Delete expired tokens): 0 */6 * * *
joplin_app.1.yi95w6wy71yq@v2202112142320170882    | 2022-03-08 22:34:43: TaskService: Scheduling #2 (Update total sizes): 0 * * * *
joplin_app.1.yi95w6wy71yq@v2202112142320170882    | 2022-03-08 22:34:43: TaskService: Scheduling #3 (Process oversized accounts): 30 */2 * * *
joplin_app.1.yi95w6wy71yq@v2202112142320170882    | 2022-03-08 22:34:43: TaskService: Scheduling #7 (Compress old changes): 0 0 */2 * *
joplin_app.1.yi95w6wy71yq@v2202112142320170882    | 2022-03-08 22:34:43: TaskService: Scheduling #8 (Process user deletions): 0 */6 * * *
joplin_app.1.yi95w6wy71yq@v2202112142320170882    | 2022-03-08 22:34:43: App: Call this for testing: `curl https://joplin.mydomain.de/api/ping`
joplin_app.1.yi95w6wy71yq@v2202112142320170882    | 2022-03-08 22:34:43: ShareService: Maintenance completed in 23ms
```
If I watch the docker service output both the database and the app service itself are up and running (replicated 1/1).
