### ISSUE TITLE
HTML button,select,option attributes broken after upgrading to 2.7.15

### ISSUE THREAD

**Issue by delolat** [laurent22/joplin#6508]
Cannot see button attributes  or select/option attributes
![image](https://user-images.githubusercontent.com/39985651/167932246-5a8a9d79-6a86-4996-bb61-c3b4f5c37119.png)
![image](https://user-images.githubusercontent.com/39985651/167932498-c6d78151-4034-49a1-a9b6-ec71e44c991c.png)

This occurred after upgrading to 2.7.15. It was working as of this morning. I tried using previous appimage versions but still does not work.

## Environment

Joplin version: 2.7.15
Platform: Linux
OS specifics: Manjaro

**Comment by Daeraxa** [comment]
What version did you upgrade from?
Can you post the actual note text/html and your userstyle.css if you have any custom css?

**Comment by delolat** [comment]
I want to say it was 2.7.11. I was upgrading to install automate notes plugin, which appeared not to work. I also do not have any custom css.

```css
	h2 {
		background-color:blue;
		padding: 20px;
		text-align:center;
	}```

```html
<h2>form</h2>
<form action="#" method="post">
<div>
	<input type="radio" name="variable_name" /> name
	<input type="radio" name="variable_name" /> name
	<input type="radio" name="variable_name2" /> name
	<input type="checkbox" name="box1" /> name
	<input type="checkbox" name="box2" /> name
	<input type="checkbox" name="box3" /> name
</div>

<select>
	<option value="test">option</option>
	<option value="test2">option2</option>
	<option value="test3">option3</option>
	<option value="test4">option4</option>
</select>

<div>
	<textarea>
default text
	</textarea>
</div>

<div>
	<input type="submit" value="Button" />
	<button type="submit">Button</button>
</div>
	<select><option>asijdadsadasdasdasdio</option></select>
```
