### ISSUE TITLE
Android: Invalid property format: 6

### ISSUE THREAD

**Issue by jtagcat** [laurent22/joplin#7480]
I upgraded the sync target on desktop, and downgraded the sync server (#7463). There are no problems on desktop.

On Android, however, sync fails with `Error: Invalid property format: 6 <dump of note body>`

The note body ends dump ends with `�D$192.�D$168.�D$!88.2f�D$%30�D$'`.

[Video Malware.jex.zip](https://github.com/laurent22/joplin/files/10254084/Video.Malware.jex.zip)

**Comment by jtagcat** [comment]
Issue perisists with latest :beta server (https://github.com/laurent22/joplin/commit/31c66ae3cdc12a13a7c767e0eed29de9cfb9f5a9)

**Comment by laurent22** [comment]
I can't replicate it with Joplin Cloud so it could be some issue with your server or proxy that's not transferring the data correctly. I see that the note is not properly displayed in Android though, due to the special characters.

**Comment by jtagcat** [comment]
I can replicate it without a proxy on two devices.

docker-compose:
```
version: '2.4'

networks:
  joplin:
#    internal: true

services:
  joplin:
    image: joplin/server:beta
    depends_on:
        - joplin-db
    restart: unless-stopped
    environment:
        - APP_PORT=22300
        - APP_BASE_URL=http://192.168.1.185:22300
        - DB_CLIENT=pg
        - POSTGRES_PASSWORD=foobar
        - POSTGRES_DATABASE=joplin
        - POSTGRES_USER=joplin
        - POSTGRES_PORT=5432
        - POSTGRES_HOST=joplin-db
    ports:
      - 22300:22300
    networks:
      - joplin
    mem_limit: 1G
  joplin-db:
    image: postgres:13
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "joplin"]
    volumes:
        - ./joplin:/var/lib/postgresql/data:rw
    restart: unless-stopped
    environment:
        - POSTGRES_PASSWORD=foobar
        - POSTGRES_USER=joplin
        - POSTGRES_DB=joplin
    networks:
      - joplin
    mem_limit: 1G
```

After the server is up, I import the JEX in a new Joplin desktop profile, and sync it successfully to the server. Joplin app v2.8.1 then fails with sync:
```
12-31T16:09:11: Synchronizer: "There was some errors:"
12-31T16:09:11: Synchronizer: "Error: On file df7f360d153848c9aea6911edf13dc37.md: Invalid property format: 6. lol windows defender: Video Malware

1. Download, extract file.
2. Inspect .bat file
3. Search for anything commonly found as part of IP or port, fail
4. certutil -decodehex -f Subtitles.srt Subtitles_tmp.srt
5. lazy ass booted up a windows VM instead
6. lol windows defender
7. Found an IP from Subtitles_tmp.srt: `�D$ 192.�D$ 168.�D$!88.2f�D$%30�D$'
index.android.bundle:996:13766
p@index.android.bundle:83:588
index.android.bundle:83:1893
index.android.bundle:996:608
f@index.android.bundle:77:207
y@index.android.bundle:77:1588
c@index.android.bundle:77:486
index.android.bundle:996:371
p@index.android.bundle:83:588
index.android.bundle:83:1893
c@index.android.bundle:1041:984
u@index.android.bundle:77:157
index.android.bundle:77:866
index.android.bundle:85:1672
k@index.android.bundle:85:500
w@index.android.bundle:85:898
callReactNativeMicrotasks@index.android.bundle:85:3054
value@index.android.bundle:38:2868
index.android.bundle:38:960
value@index.android.bundle:38:2504
value@index.android.bundle:38:919
value@[native code]
value@[native code]"
```

I suspected that there might be something about the phone's software stack itself. Using OnePlus 5t (dumpling) with LineageOS.

I was also able to reproduce on Umidigi Crystal (Android 7), but on the second try.

First time it ignored the existence of the note, and synced successfully. (I didn't notice it.) After that, dumpling was able to sync as well (ignoring the file, syncing everything else without any error being displayed).  
Removing and readding the note on desktop results in the issue being reproducible on both phones. I skimmed the on-device logs for any indication of this, but didn't find anything.

Also: it'd be nice if logs could be copied out of the app more than one line at a time using an external helper app to force it.

If I get access to Joplin Cloud, I can try to replicate there as well.
