### ISSUE TITLE
Links not working for a custom button, only in full preview mode. Link works fine in dual pane mode.

### ISSUE THREAD

**Issue by futuremotiondev** [laurent22/joplin#8299]
## Environment

Joplin version: 2.10.19
Platform: Windows
OS specifics: Win10 Pro x64 22H2

## Steps to reproduce

My code:

```html
<div><a href="http://www.google.com"><vsys-btn class="gray"><span class="icon-info-circle"></span><p>This is a gray button</p></vsys-btn></a></div>
```

Screenshot:

![explorer_3rlDPPwD6R](https://github.com/laurent22/joplin/assets/33441569/9d7831c7-9cd1-41f1-9800-6c3afb88c987)

I have some custom CSS styling for the vsys-btn tag to make it look like a button as you can see above. When I'm in dual pane mode, I can click the button and it works fine. But if I toggle the editor to just show rendered markdown, the links no longer work.

Here's another screenshot showing that the button is in-fact wrapped in an `a` tag:

![firefox_0umBxJO4No](https://github.com/laurent22/joplin/assets/33441569/864ac027-bb11-49e9-a15c-5b478457ba98)

## Describe what you expected to happen

I expect the button to function normally.

**Comment by laurent22** [comment]
Not sure if related but the class jop-noMdConv is for internal use, and is now cleared when loading the note.

Other than that, I don't really understand the issue based on the screenshot and explanation

**Comment by dpoulton-github** [comment]
**Observation**

Your screenshots suggest that you are not toggling between the Markdown editor "dual pane" and the Markdown editor's single pane viewer, but between the Markdown editor "dual pane" and the WYSIWYG editor.

![screen1](https://github.com/laurent22/joplin/assets/60117449/056ca369-735c-48bc-a384-4ce104448282)
![screen2](https://github.com/laurent22/joplin/assets/60117449/8e530329-0b3f-477c-8983-2e9492d01ae1)

In the WYSIWYG editor links are followed using CTRL+click but even this does not work with your button. I have duplicated this. So your button works in the Markdown editor's viewer but not in the WYSIWYG editor. *Why this is I do not know.*

However, rather than use the WYSIWYG editor as a "viewer" you can **remain in the Markdown editor** and **switch between different views** - _editor only_, _editor and viewer_ (your first screenshot) and _viewer only_ - by keeping the "M↓" button active and using the toolbar "Toggle editor layout" button (see image), or CTRL+L, or **View** > **Toggle editor layout**.

If your button works in the Markdown viewer of the "dual pane" view it should also work in the viewer only view.

![markdown_switching](https://github.com/laurent22/joplin/assets/60117449/39755d19-75ca-4c43-a60b-8c79dfb373bd)

What views this button toggles through can be changed using **View** > **Layout button sequence**.

This does not solve the problem as to why the styled \<a\> link does not work in the WYSIWYG editor, but it does allow you to use your button.

**Comment by futuremotiondev** [comment]
@dpoulton-github Thanks for all that info. Glad to know that the buttons will work when I go to the `viewer only` view. 

I'd really like them to work in the WYSIWYG editor though. Hopefully some kind of patch or update will get pushed.

**Comment by futuremotiondev** [comment]
@laurent22 I'm not making any use of `jop-noMdConv` in my CSS or HTML. So I don't think that's an issue.

The problem is:

1. I can click my button in the markdown preview window in dual pane mode.
2. I can click my button in the full page markdown preview window.
3. I **cannot** click my button in the WYSIWYG editor. 

HTML:

```html
<a href="http://www.google.com"><vsys-btn class="blue"><span class="icon-info-circle"></span>This is a blue button</vsys-btn></a>
<a href="http://www.google.com"><vsys-btn class="gray"><span class="icon-info-circle"></span>This is a gray button</vsys-btn></a>
```

CSS:

```css
vsys-btn {
   background-color: #fff;
   border-radius: 0.3125rem;
   display: inline-flex;
   font-size: 0.96rem;
   margin-top: 0.5rem;
   margin-bottom: 0.5rem;
   margin-left: 0rem;
   margin-right: 0.6rem;
   padding: 0.8rem;
   font-weight: 400;
   font-family: "Helvetica LT Pro", "Helvetica", "Arial", sans-serif;
   line-height: 1.4rem;
   color: #5b5e66;
   border: 1px solid #aaa;
   max-width: fit-content;
   align-items: center;
}

vsys-btn span {
   font-size: var(--icon-vsmall);
   margin-right: var(--icon-vsmall-margin);
}

vsys-btn.blue {
   background-color: var(--icon-color-info);
   color: var(--icon-color-white);
   border: 1px solid var(--icon-color-info);
}

vsys-btn.gray {
   background-color: var(--icon-color-white);
   color: var(--icon-color-neutral-3);
   border: 1px solid #aaa;
}

vsys-btn.gray span {
    color: var(--icon-color-neutral-1);
}

vsys-btn p {
    margin-top: 0em;
    margin-bottom: 0em;
    padding-top: 3px;
}
```

It would be great if there was a way to get this to work in WYSIWYG mode. 

Would you consider a patch?

Hopefully this clarifies the issue further for you.

**Edit:**

Just wanted to also specify that control-clicking on the button in the WYSIWYG editor doesn't work either.

**Edit 2:**

I took a screenshot of the live HTML code in the WYSIWYG editor via Devtools.

![Joplin_R0O2HUuONw](https://github.com/laurent22/joplin/assets/33441569/e7fe798f-8f82-4655-9242-a12302f07c8b)

So as you can see the `a` tags are still there.
