### ISSUE TITLE
"“" cannot display correctly in blockquote:before

### ISSUE THREAD

**Issue by h888866j** [laurent22/joplin#8474]
## Environment

Joplin version: 
Joplin 2.11.9 (prod, win32)

Client ID: f1b2a3f4f2af42eea8e2b885bfa5ccea
Sync Version: 3
Profile Version: 42
Keychain Supported: Yes

Revision: 30671e7

Folding in Code Mirror Editor: 2.0.1
Rich Markdown: 0.7.3

Platform: Windows10
OS specifics:   Microsoft Windows [Version 10.0.15063]

## Steps to reproduce

1.  create a markdown file and cite something in it
```markdown
>Cited something from somewhere
```
2. add css to userstyle.css
```css
#rendered-md blockquote:before {
    content: "“";
    display: inline;
    color: #555555;
    font-size: 4em;
    font-family: Optima-Regular, Optima, PingFangSC-light, PingFangTC-light, 'PingFang SC', Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;
    line-height: 1em;
    font-weight: 700;
   
}

```
3. restart Joplin, it cannot display "”" before the cited text， instead it displays two "?"

## Describe what you expected to happen

restart Joplin, it cannot display "”" before the cited text， instead it displays two "?"
![image](https://github.com/laurent22/joplin/assets/16606957/9d18ad93-366d-4ff9-bba0-8b4383afc87c)

it should display like follow:
![image](https://github.com/laurent22/joplin/assets/16606957/178b75e8-abfb-4333-80b7-8d87fac4434c)

after export to HTML and open in Chrome, it still shows two "?".

**Comment by h888866j** [comment]
Nevermind. "\201c" resolves the issue

```css
#rendered-md blockquote:before {
    content: "\201c";
    display: inline;
    color: #555555;
    font-size: 4em;
    font-family: Arial, serif;
    line-height: 1em;
    font-weight: 700;
   
}

```
