### ISSUE TITLE
Joplin Server Container Permission Issues

### ISSUE THREAD

**Issue by zeyadtamimi** [laurent22/joplin#9489]
### Operating system

Linux

### Joplin version

2.13.3

### Issue

When creating a rootless podman Joplin server container 

```
podman run -d \
   --name "$APP_NAME" \
   --pod "$POD_NAME" \
   --restart=unless-stopped \
   -e POSTGRES_PASSWORD=$DB_PWD \
   -e POSTGRES_USER=$DB_USER \
   -e POSTGRES_DB=$DB_DB_NAME \
   -e DB_CLIENT=pg \
   -e APP_PORT=21200 \
   -e POSTGRES_HOST="::1" \
   -e POSTGRES_PORT=5432 \
   $APP_IMAGE
```

I get a strange permissions failure inside the container along the lines of:

```
 warning Skipping preferred cache folder "/home/joplin/.cache/yarn" because it is not writable.
 warning Selected the next writable cache folder in the list, will be "/tmp/.yarn-cache-1001".
 $ pm2 kill && pm2 start --no-daemon --exp-backoff-restart-delay=1000 dist/app.js
 warning Cannot find a suitable global folder. Tried these: "/usr/local, /home/joplin/.yarn"
 - [10/Dec/2023:23:20:12 -0800] "GET /v1.12/libpod/containers/8cb5b853e0be0ccd9b051aaa2d93ad48a9b63bdd396ba0f41cbb0a93b1ac4914/json?size=false HTTP/1.1" 200 8337 "" ""
 Error: EACCES: permission denied, mkdir '/home/joplin/.pm2/logs'
     at Object.mkdirSync (node:fs:1398:3)
     at mkdirpNativeSync (/home/joplin/packages/server/node_modules/mkdirp/lib/mkdirp-native.js:29:10)
     at Function.mkdirpSync [as sync] (/home/joplin/packages/server/node_modules/mkdirp/index.js:21:7)
     at Client.initFileStructure (/home/joplin/packages/server/node_modules/pm2/lib/Client.js:133:25)
     at new module.exports (/home/joplin/packages/server/node_modules/pm2/lib/Client.js:38:8)
     at new API (/home/joplin/packages/server/node_modules/pm2/lib/API.js:107:19)
     at Object.<anonymous> (/home/joplin/packages/server/node_modules/pm2/lib/binaries/CLI.js:22:11)
     at Module._compile (node:internal/modules/cjs/loader:1256:14)
     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
     at Module.load (node:internal/modules/cjs/loader:1119:32)
 Error: EACCES: permission denied, mkdir '/home/joplin/.pm2/pids'
     at Object.mkdirSync (node:fs:1398:3)
     at mkdirpNativeSync (/home/joplin/packages/server/node_modules/mkdirp/lib/mkdirp-native.js:29:10)
     at Function.mkdirpSync [as sync] (/home/joplin/packages/server/node_modules/mkdirp/index.js:21:7)
     at Client.initFileStructure (/home/joplin/packages/server/node_modules/pm2/lib/Client.js:141:25)
     at new module.exports (/home/joplin/packages/server/node_modules/pm2/lib/Client.js:38:8)
     at new API (/home/joplin/packages/server/node_modules/pm2/lib/API.js:107:19)
     at Object.<anonymous> (/home/joplin/packages/server/node_modules/pm2/lib/binaries/CLI.js:22:11)
     at Module._compile (node:internal/modules/cjs/loader:1256:14)
     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
     at Module.load (node:internal/modules/cjs/loader:1119:32)
 Error: ENOENT: no such file or directory, open '/home/joplin/.pm2/module_conf.json'
     at Object.openSync (node:fs:603:3)
     at Object.writeFileSync (node:fs:2324:35)
     at Client.initFileStructure (/home/joplin/packages/server/node_modules/pm2/lib/Client.js:149:10)
     at new module.exports (/home/joplin/packages/server/node_modules/pm2/lib/Client.js:38:8)
     at new API (/home/joplin/packages/server/node_modules/pm2/lib/API.js:107:19)
     at Object.<anonymous> (/home/joplin/packages/server/node_modules/pm2/lib/binaries/CLI.js:22:11)
     at Module._compile (node:internal/modules/cjs/loader:1256:14)
     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
     at Module.load (node:internal/modules/cjs/loader:1119:32)
     at Module._load (node:internal/modules/cjs/loader:960:12)
 Error: EACCES: permission denied, mkdir '/home/joplin/.pm2/modules'
     at Object.mkdirSync (node:fs:1398:3)
     at mkdirpNativeSync (/home/joplin/packages/server/node_modules/mkdirp/lib/mkdirp-native.js:29:10)
     at Function.mkdirpSync [as sync] (/home/joplin/packages/server/node_modules/mkdirp/index.js:21:7)
     at Client.initFileStructure (/home/joplin/packages/server/node_modules/pm2/lib/Client.js:157:25)
     at new module.exports (/home/joplin/packages/server/node_modules/pm2/lib/Client.js:38:8)
     at new API (/home/joplin/packages/server/node_modules/pm2/lib/API.js:107:19)
     at Object.<anonymous> (/home/joplin/packages/server/node_modules/pm2/lib/binaries/CLI.js:22:11)
     at Module._compile (node:internal/modules/cjs/loader:1256:14)
     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
     at Module.load (node:internal/modules/cjs/loader:1119:32)
```

I am confused as to why there would be any permissions issues given the fact that from the container's point of view it has full root access ( even if the container is run as a non root user ).

I tried mucking around with UIDs/GIDs and passing different ones to the container with no avail :(

Any help with debugging this would greatly be appreciated.

**Comment by zeyadtamimi** [comment]
Update: Something is messed up in the container and it appears that the user ID for the home dir is completely out of whack....

```> podman run --name test --replace docker.io/joplin/server:2.13.4-beta ls -la /home
total 2
drwxr-xr-x 1 root root   3 Nov 15 15:35 .
dr-xr-xr-x 1 root root   4 Dec 13 04:11 ..
drwxr-xr-x 1 1002 joplin 3 Nov 15 15:38 joplin
drwxr-xr-x 2 1004   1003 5 Nov  1 07:23 node
```

Im kind of confused how this could be the case given the above run command.

**Comment by bphenriques** [comment]
I am facing the exact issue (running as non-root intentionaly though):
```yaml
  # https://github.com/laurent22/joplin/blob/dev/docker-compose.server.yml. Exposes 5432
  joplin-db:
    image: postgres:16
    hostname: joplin-db
    container_name: joplin-db
    user: "${PUID}:${PGID}"
    volumes:
      - "${DATA_DIR}/joplin-db:/var/lib/postgresql/data"
    restart: unless-stopped
    env_file:
      - .env
      - .env.joplin.private
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - POSTGRES_DB=joplin
    networks:
      - joplin

  # https://github.com/laurent22/joplin/blob/dev/docker-compose.server.yml. Exposes 22300
  joplin-app:
    image: joplin/server:latest
    hostname: joplin-app
    container_name: joplin-app
    user: "${PUID}:${PGID}"
    depends_on:
      - joplin-db
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - APP_PORT=22300
      - DB_CLIENT=pg
      - POSTGRES_DATABASE=joplin
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=joplin-db
    networks:
      - joplin
      - public
```

Related: https://discourse.joplinapp.org/t/joplin-server-error-cant-run-without-root/30619

**Comment by AdrienPoupa** [comment]
I'm having the same issue here, preventing me from using bind mounts and volumes.

My local user is `1000` but the server image uses the `joplin` user that's `1001`, `node` being `1000`.

When I don't specify the user in Docker compose, Joplin can't read the bind mounts / volumes since they're owned by root. When I specify my user, I'm getting the logs permission issue:

```
joplin  | 01:51:52 0|app    | [Error: EACCES: permission denied, mkdir '/home/joplin/packages/server/logs'] {
joplin  | 01:51:52 0|app    |   errno: -13,
joplin  | 01:51:52 0|app    |   code: 'EACCES',
joplin  | 01:51:52 0|app    |   syscall: 'mkdir',
joplin  | 01:51:52 0|app    |   path: '/home/joplin/packages/server/logs'
joplin  | 01:51:52 0|app    | }
```

**Comment by falkheiland** [comment]
any news here?

**Comment by martinkozle** [comment]
Same issue here!

**Comment by zeyadtamimi** [comment]
Regarding the permissions issue where directories in the container's overlay FS have messed up permissions I was never really able to debug why that occurs, that being said, I was also not able to reproduce for some time now.

The solution I used to get around this was to delete the image from podman ( not just the container ) and re-pull the image and recreate the container. I hope this can help others who run into something similar.

As I have not been able to reproduce this I will close the issue, for other commenters hitting different but permissions related issues I think those should be their own threads.

**Comment by banigithub-2** [comment]
I seem to have this issue, having rebooted my QNAP NAS after a while.
Running joplin server as a docker container, with a pg container alongside.
Elected to recreate both containers using the published docker-compose.yml / .env with the contents locally customised to make sure there wasn't any issue.

It seems to be an issue with the container having permission to access files within the container?!  I'm not sure how I can fix that?  Any suggestions would be very welcome!

Error in joplin app container logs:


```
Error: ENOENT: no such file or directory, open '/.pm2/module_conf.json'
    at Object.openSync (node:fs:596:3)
    at Object.readFileSync (node:fs:464:35)
    at Configuration.getAllSync (/home/joplin/packages/server/node_modules/pm2/lib/Configuration.js:299:26)
    at Configuration.getSync (/home/joplin/packages/server/node_modules/pm2/lib/Configuration.js:270:30)
    at new API (/home/joplin/packages/server/node_modules/pm2/lib/API.js:116:44)
    at Object.<anonymous> (/home/joplin/packages/server/node_modules/pm2/lib/binaries/CLI.js:22:11)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
node:internal/fs/utils:351
    throw err;
    ^
Error: ENOENT: no such file or directory, open '/.pm2/pm2.log'
    at Object.openSync (node:fs:596:3)
    at Client.launchDaemon (/home/joplin/packages/server/node_modules/pm2/lib/Client.js:228:12)
    at /home/joplin/packages/server/node_modules/pm2/lib/Client.js:104:10
    at /home/joplin/packages/server/node_modules/pm2/lib/Client.js:321:14
    at processTicksAndRejections (node:internal/process/task_queues:77:11)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at listOnTimeout (node:internal/timers:538:9)
    at process.processTimers (node:internal/timers:512:7) {
```

docker-compose.yml is:

```
version: '3'

services:
    db:
        image: postgres:13.1
        container_name: "joplin-db"
        user: "1006:100"
        volumes:
            - ../../_data/joplin-db/postgres:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        restart: unless-stopped
        environment:
            - POSTGRES_PASSWORD=secret
            - POSTGRES_USER=joplin
            - POSTGRES_DB=joplin
            - PG_MAJOR=13
            - PG_VERSION=13.1-1.pgdg100+1
            - PGDATA=/var/lib/postgresql/data
            - PUID=1006
            - PGID=100
        networks:
            - traefik_default
    app:
        image: joplin/server:latest
        container_name: "joplin-app"
        user: "1006:100"
        depends_on:
            - db
        ports:
            - "22300:22300"
        restart: unless-stopped
        environment:
            - PUID=1006
            - PGID=100
            - APP_PORT=22300
            - APP_BASE_URL=https://secret
            - DB_CLIENT=pg
            - POSTGRES_PASSWORD=secret
            - POSTGRES_DATABASE=joplin
            - POSTGRES_USER=joplin
            - POSTGRES_PORT=5432
            - POSTGRES_HOST=db
            - MAILER_AUTH_PASSWORD=secret
            - MAILER_AUTH_USER=secret
            - MAILER_ENABLED=1
            - MAILER_HOST=secret
            - MAILER_NOREPLY_EMAIL=secret
            - MAILER_NOREPLY_NAME=JoplinServer
            - MAILER_PORT=587
            - MAILER_SECURITY=starttls
            - NODE_ENV=production
        labels:
            - traefik.enable=true
            - traefik.http.routers.joplin.entrypoints=websecure
            - traefik.http.routers.joplin.rule=Host(`secret`)
            - traefik.http.routers.joplin.tls.certresolver=myresolver
        networks:
            - traefik_default

networks:
    traefik_default:
        external: true
```

**Comment by valmar** [comment]
If the host is RedHat Enterprise Linux or one of the clones (like CentOS), the problem could be caused by Selinux and the security options of docker containers. This would explain why it is so hard to reproduce (by  people using non-Red Hat hosts).

I had the same problem, and it seems solved by adding the following lines for every container in `docker-compose.yml`:

```
security_opt:
  - "label:disable"
```

And using `user: 1001:1001`

**Comment by 0xFFA500** [comment]
> I seem to have this issue, having rebooted my QNAP NAS after a while. Running joplin server as a docker container, with a pg container alongside. Elected to recreate both containers using the published docker-compose.yml / .env with the contents locally customised to make sure there wasn't any issue.
> 
> It seems to be an issue with the container having permission to access files within the container?! I'm not sure how I can fix that? Any suggestions would be very welcome!
> 
> Error in joplin app container logs:
> 
> ```
> Error: ENOENT: no such file or directory, open '/.pm2/module_conf.json'
>     at Object.openSync (node:fs:596:3)
>     at Object.readFileSync (node:fs:464:35)
>     at Configuration.getAllSync (/home/joplin/packages/server/node_modules/pm2/lib/Configuration.js:299:26)
>     at Configuration.getSync (/home/joplin/packages/server/node_modules/pm2/lib/Configuration.js:270:30)
>     at new API (/home/joplin/packages/server/node_modules/pm2/lib/API.js:116:44)
>     at Object.<anonymous> (/home/joplin/packages/server/node_modules/pm2/lib/binaries/CLI.js:22:11)
>     at Module._compile (node:internal/modules/cjs/loader:1356:14)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
>     at Module.load (node:internal/modules/cjs/loader:1197:32)
>     at Module._load (node:internal/modules/cjs/loader:1013:12)
> node:internal/fs/utils:351
>     throw err;
>     ^
> Error: ENOENT: no such file or directory, open '/.pm2/pm2.log'
>     at Object.openSync (node:fs:596:3)
>     at Client.launchDaemon (/home/joplin/packages/server/node_modules/pm2/lib/Client.js:228:12)
>     at /home/joplin/packages/server/node_modules/pm2/lib/Client.js:104:10
>     at /home/joplin/packages/server/node_modules/pm2/lib/Client.js:321:14
>     at processTicksAndRejections (node:internal/process/task_queues:77:11)
>     at runNextTicks (node:internal/process/task_queues:64:3)
>     at listOnTimeout (node:internal/timers:538:9)
>     at process.processTimers (node:internal/timers:512:7) {
> ```
> 
> docker-compose.yml is:
> 
> ```
> version: '3'
> 
> services:
>     db:
>         image: postgres:13.1
>         container_name: "joplin-db"
>         user: "1006:100"
>         volumes:
>             - ../../_data/joplin-db/postgres:/var/lib/postgresql/data
>         ports:
>             - "5432:5432"
>         restart: unless-stopped
>         environment:
>             - POSTGRES_PASSWORD=secret
>             - POSTGRES_USER=joplin
>             - POSTGRES_DB=joplin
>             - PG_MAJOR=13
>             - PG_VERSION=13.1-1.pgdg100+1
>             - PGDATA=/var/lib/postgresql/data
>             - PUID=1006
>             - PGID=100
>         networks:
>             - traefik_default
>     app:
>         image: joplin/server:latest
>         container_name: "joplin-app"
>         user: "1006:100"
>         depends_on:
>             - db
>         ports:
>             - "22300:22300"
>         restart: unless-stopped
>         environment:
>             - PUID=1006
>             - PGID=100
>             - APP_PORT=22300
>             - APP_BASE_URL=https://secret
>             - DB_CLIENT=pg
>             - POSTGRES_PASSWORD=secret
>             - POSTGRES_DATABASE=joplin
>             - POSTGRES_USER=joplin
>             - POSTGRES_PORT=5432
>             - POSTGRES_HOST=db
>             - MAILER_AUTH_PASSWORD=secret
>             - MAILER_AUTH_USER=secret
>             - MAILER_ENABLED=1
>             - MAILER_HOST=secret
>             - MAILER_NOREPLY_EMAIL=secret
>             - MAILER_NOREPLY_NAME=JoplinServer
>             - MAILER_PORT=587
>             - MAILER_SECURITY=starttls
>             - NODE_ENV=production
>         labels:
>             - traefik.enable=true
>             - traefik.http.routers.joplin.entrypoints=websecure
>             - traefik.http.routers.joplin.rule=Host(`secret`)
>             - traefik.http.routers.joplin.tls.certresolver=myresolver
>         networks:
>             - traefik_default
> 
> networks:
>     traefik_default:
>         external: true
> ```

Did you figure out a way to run it as a non root user?

I'm having the same issue.
<details><summary>Details</summary>
<p>

```yaml
services:
  joplin:
    container_name: joplin
    depends_on:
      - postgres
    environment:
      - APP_BASE_URL=https://joplin.👀
      - APP_PORT=22300
      - DB_CLIENT=pg

      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=joplin
      - POSTGRES_USER=joplin
      - POSTGRES_PASSWORD=👀

      - MAILER_ENABLED=1
      - MAILER_HOST=mail.👀.com
      - MAILER_PORT=465
      - MAILER_SECURE=1
      - MAILER_AUTH_USER=joplin@👀
      - MAILER_AUTH_PASSWORD=👀
      - MAILER_NOREPLY_NAME=Joplin
      - MAILER_NOREPLY_EMAIL=joplin@👀
    image: joplin/server
    labels:
      - traefik.enable=true
      - traefik.docker.network=joplin

      - traefik.http.routers.joplin.entryPoints=webSecure
      - traefik.http.routers.joplin.rule=Host(`joplin.👀`)
      - traefik.http.services.joplin.loadBalancer.server.port=22300
      - traefik.http.routers.joplin.service=joplin
    networks:
      - joplin
      - postgres
    restart: unless-stopped
    user: 1008:1008
```

</p>
</details>
