### ISSUE TITLE
Nextcloud sync: Very easy to cause data corruption with Nextcloud's rich text editor

### ISSUE THREAD

**Issue by personalizedrefrigerator** [laurent22/joplin#9887]
### Operating system

Linux

### Joplin version

2.14.12

### Current behaviour

1. Open a file on the Nextcloud web interface (left-click)
2. Leave open for about 30 seconds (long enough to auto-save)
3. Try to sync Joplin

Currently,
```yaml
id: 36dc5bb035a0433da224b8fcc0368081
parent_id: 
item_type: 1
item_id: ee829a38b5e84cd48d74aeee602b1e72
item_updated_time: 1707265701979
title_diff: "[{\"diffs\":[[1,\"Test NUL 2\"]],\"start1\":0,\"start2\":0,\"length1\":0,\"length2\":10}]"
body_diff: "[{\"diffs\":[[1,\"Test NUL 2\\\n\\\n\\\n\\\n[js-draw.pdf](:/3529017ac0974c8a8fd463f60b3d16a8)\\\n\\\n\"]],\"start1\":0,\"start2\":0,\"length1\":0,\"length2\":65}]"
metadata_diff: {"new":{"id":"ee829a38b5e84cd48d74aeee602b1e72","parent_id":"248e9425a4e042cda71d51f42b6d498f","latitude":"123.45678","longitude":"9101112.13141","altitude":"0.0000","author":"","source_url":"","is_todo":0,"todo_due":0,"todo_completed":0,"source":"joplindev-desktop","source_application":"net.cozic.joplindev-desktop","application_data":"","order":0,"markup_language":1,"is_shared":0,"share_id":"","conflict_original_id":"","master_key_id":"","user_data":""},"deleted":[]}
encryption_cipher_text: 
encryption_applied: 0
updated_time: 2024-02-07T00:34:40.150Z
created_time: 2024-02-07T00:34:40.150Z
type_: 13
```
becomes
```yaml
id: 36dc5bb035a0433da224b8fcc0368081
parent_id:
item_type: 1
item_id: ee829a38b5e84cd48d74aeee602b1e72
item_updated_time: 1707265701979
title_diff: "[{"diffs":\[\[1,"Test NUL 2"\]\],"start1":0,"start2":0,"length1":0,"length2":10}]"
body_diff: "[{"diffs":\[\[1,"Test NUL 2\\\\n\\\\n\\\\n\\\\n[js-draw.pdf](:/3529017ac0974c8a8fd463f60b3d16a8)\\\\n\\\\n"\]\],"start1":0,"start2":0,"length1":0,"length2":65}]"
metadata_diff: {"new":{"id":"ee829a38b5e84cd48d74aeee602b1e72","parent_id":"248e9425a4e042cda71d51f42b6d498f","latitude":"123.45678","longitude":"9101112.13141","altitude":"0.0000","author":"","source_url":"","is_todo":0,"todo_due":0,"todo_completed":0,"source":"joplindev-desktop","source_application":"net.cozic.joplindev-desktop","application_data":"","order":0,"markup_language":1,"is_shared":0,"share_id":"","conflict_original_id":"","master_key_id":"","user_data":""},"deleted":\[\]}
encryption_cipher_text:
encryption_applied: 0
updated_time: 2024-02-07T00:34:40.150Z
created_time: 2024-02-07T00:34:40.150Z
type\_: 13
```

Sync with Joplin then fails (key `type_` not found).

### Expected behaviour

Either
1. Joplin should be able to handle characters escaped by Nextcloud
    - **Edit**: This doesn't seem feasible &mdash; Nextcloud changes more than just `type_` -> `type\_` (compare `body_diff` and `title_diff` above).
3. It shouldn't be possible to edit Joplin sync files in Nextcloud's rich text editor UI (e.g. make them use a `.yaml` extension)
    - **Edit**: This isn't feasible either &mdash; see below.
