### ISSUE TITLE
Text in the spellcheck button is wrapping

### ISSUE THREAD

**Issue by HahaBill** [laurent22/joplin#9998]
### Operating system

macOS

### Joplin version

2.13.15

### Desktop version info

Joplin 2.13.15 (prod, darwin)

Client ID: c08e549cb29947a58cf80d908c0a74a3
Sync Version: 3
Profile Version: 44
Keychain Supported: No

Revision: 7d2c1c0

### Current behaviour

The current behavior is that when I add multiple spellcheck languages, the button's text wraps as shown in two pictures below.

<img width="826" alt="Screenshot 2024-02-25 at 11 08 39" src="https://github.com/laurent22/joplin/assets/32552798/fa92453d-3958-4ef4-a4a4-28a258544688">

<img width="593" alt="Screenshot 2024-02-25 at 11 09 42" src="https://github.com/laurent22/joplin/assets/32552798/09853945-aca0-47ab-b011-c86c695c4b34">

### Expected behaviour

The text should not wrap. Here are suggested solutions:

#### Solution 1:
```css
someElement {
  .
  .
  .
  white-space: nowrap; 
  overflow: hidden;
  text-overflow: ellipsis;
  
}
```

#### Solution 2:
```css
someElement {
  .
  .
  .
  white-space: nowrap; 
  overflow-x: scroll;
  &::-webkit-scrollbar {
       display: none;
  }
  
}
```
